<a href="https://colab.research.google.com/github/istiaq27/Data-Analysis-Using-Python/blob/main/Numpy%20Basic/2.%20Using%20arrays%20and%20scalars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [8]:
#Takes care of floats
# for python 2.x
# from __future__ import division

In [6]:
5/2

2.5

In [4]:
5//2

2

In [10]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])

#Show
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [11]:
#Multiplying Arrays
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [12]:
#Subtraction
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
#Arithmetic operations with scalars on array

1 // arr1

array([[1, 0, 0],
       [0, 0, 0]])

In [17]:
1 / np.array([1,2,3])

array([1.        , 0.5       , 0.33333333])

In [19]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]])