<a href="https://colab.research.google.com/github/istiaq27/Data-Analysis-Using-Python/blob/main/Numpy%20Basic/5.%20Universal%20Array%20Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [2]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.sqrt(9)

3.0

In [3]:
#Taking Square Roots

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [9]:
#Calcualting exponential (e^)

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [33]:
# Get the element-wise maximum of two arrays

a1 = [0, 1, 0]
a2 = [1, 0, 7]
np.maximum(a1, a2)

array([1, 1, 7])

In [30]:
# Random int number between 2 to 7(excluding) ; total 10 random int
x = np.random.randint(2,7,size=10)
x

array([4, 3, 3, 4, 4, 6, 2, 4, 6, 2])

In [29]:
y = np.random.randint(2,9,size=10)
y

array([8, 6, 8, 5, 2, 3, 3, 5, 7, 6])

In [26]:
# Addition of 2 array
np.add(x,y)

array([10, 12, 11, 13, 10,  6, 11,  5,  7, 10])

In [31]:
#Finding max or min between two arrays
np.maximum(x,y)

array([8, 6, 8, 5, 4, 6, 3, 5, 7, 6])

In [10]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)
A

array([ 0.29078849, -2.11656347,  0.75832565, -0.8269859 , -1.14144057,
       -0.48026588, -0.16664872,  0.37230145,  0.82100011, -0.72266548])

In [11]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-1.69469706,  0.51793249,  1.8439338 ,  2.69752304, -0.8584643 ,
        1.01019639,  1.85188996,  0.51516846,  0.32868745,  0.10607354])

In [18]:
#Addition
np.add(A,B)

array([-1.40390856, -1.59863098,  2.60225946,  1.87053714, -1.99990487,
        0.52993051,  1.68524124,  0.88746991,  1.14968756, -0.61659194])

In [34]:
#Finding max or min between two arrays
np.maximum(A,B)

array([ 0.29078849,  0.51793249,  1.8439338 ,  2.69752304, -0.8584643 ,
        1.01019639,  1.85188996,  0.51516846,  0.82100011,  0.10607354])

In [35]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

False