<a href="https://colab.research.google.com/github/istiaq27/Data-Analysis-Using-Python/blob/main/Numpy%20Basic/7.%20Array%20Input%20and%20Output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Create an array
arr = np.arange(5)

In [3]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',arr)

In [4]:
#Change arr
arr = np.arange(10)
#Show
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Lets see the original saved copy
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [7]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=arr,y=arr)

In [8]:
#Now loading multiple arrays
archive_array = np.load('two_arrays.npz')

#Show
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#Now lets remove them from the memory
# rm my_array.npy
# rm two_arrays.npz

In [10]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [11]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr


array([[1., 2., 3.],
       [4., 5., 6.]])